project_name: goreleaser-example
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: ["ghcr.io/tuxcanfly/goreleaser-example:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/tuxcanfly/goreleaser-example
  - --label=org.opencontainers.image.source=https://github.com/tuxcanfly/goreleaser-example
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
nfpms:
- maintainer: Javed Khan <tuxcanfly@gmail.com>
  description: goreleaser example project.
  homepage: https://github.com/tuxcanfly/goreleaser-example
  license: MIT
  formats:
  - deb
  - rpm
  - apk
